### ISSUE TITLE
Syncing variable products and skipping _price 

### ISSUE THREAD

**Issue by mikaelmattsson** [the-plainview/threewp_broadcast#27]
This might be related to the pro version of this plugin but for obvious reasons i could not find a repository for that plugin. I want products to sync between sites/shops but i want to set the prices individually. This works fine with simple products, but when I sync a variable product I get the following warning message:

    Warning: reset() expects parameter 1 to be array, null given in path/wp-content/plugins/threewp-broadcast-premium-pack/src/woocommerce/WooCommerce.php on line 264
    Warning: reset() expects parameter 1 to be array, null given in path/wp-content/plugins/threewp-broadcast-premium-pack/src/woocommerce/WooCommerce.php on line 264
    Warning: reset() expects parameter 1 to be array, null given in path/wp-content/plugins/threewp-broadcast-premium-pack/src/woocommerce/WooCommerce.php on line 264
    Warning: reset() expects parameter 1 to be array, null given in path/wp-content/plugins/threewp-broadcast-premium-pack/src/woocommerce/WooCommerce.php on line 264

In addition, the variations get kind of corrupt and are will not activate even after I set a price for them. The same thing happens when I use the “send to many” feature. The send to many and and woocommerce are the only premium features I have activated.

I have only set a single field, _price, in the “Internal field blacklist”

I also what to thank you for making this awesome plugin.

**Comment by the-plainview** [comment]
Sounds like you need to switch on broadcast debug mode, broadcast your post and then show me the enormous debug dump so that we can try and follow what is going on.

Email me the dump at edward@plainviewplugins.com

**Comment by mikaelmattsson** [comment]
Sent
