### ISSUE TITLE
Javascript error on clicking child's "broadcasted by" link (for unlinking popup)

### ISSUE THREAD

**Issue by jaapbaardaap** [the-plainview/threewp_broadcast#28]
The error I get is:
```
Uncaught TypeError: Cannot read property 'replace' of undefined
```

This is because in my installation this row does not have class level-0 but:
```html
<tr id="post-245" class="post-245 type-page status-publish hentry alternate iedit author-self level-1">
```
After searching I found this level has something to do with authority level and not level in the dom.

The code causing the error is at line 121 of js.js namely:
```javascript
// Get the post ID.
$tr = $this.parentsUntil( 'tr.level-0' ).parent();
var id = $tr.prop( 'id' ).replace( 'post-', '' );
```
I've fixed it by changing that code to:
```javascript
// Get the post ID.
$tr = $this.parentsUntil( 'tbody#the-list' ).last();
var id = $tr.prop( 'id' ).replace( 'post-', '' );
```

**Comment by the-plainview** [comment]
Won't last() select the last tr in the table?

**Comment by jaapbaardaap** [comment]
I'm no javascript expert but parentsUntil gives a object with all elements from the starting element till the element with a matching parent. Because this function works it's way up the dom I think the last element is the top most element. You could also use a different method of selecting the td element but level-0 is not a correct selector.

**Comment by the-plainview** [comment]
Accepted your fix. It seems to choose the correct line all the time.

Modified the source js file (not the comibined js.js file). See https://github.com/the-plainview/threewp_broadcast/commit/fadaadd9775bee9c2a7156355aa25edf4bff29ec
