### ISSUE TITLE
Warning in src/sdk/wordpress/base.php

### ISSUE THREAD

**Issue by noelboss** [the-plainview/threewp_broadcast#30]
Warning: Illegal offset type in …wp-content/plugins/threewp-broadcast/src/sdk/wordpress/base.php on line 444

**Comment by the-plainview** [comment]
Have you tried resaving all of your roles?

**Comment by noelboss** [comment]
How do I do this? Actually, this warning is only showing up sporadically, I tried to debug the code but I don't even get the message now. I saw this error yesterday, and today I got a message from a user with the same error, but I don't see the warning now…

**Comment by the-plainview** [comment]
Just go to your admin settings, where you can set all of the roles to broadcast, and update the settings. Should solve the problem.

**Comment by noelboss** [comment]
Shouldn't you check if its an array and act acrodingly?

I'm not totaly sure what the code does, but i suspect that you should abort when $roles  is not an array and return true or false depending on whatever the functions is meant to return in this case...

```
// Line 443+
	$roles = $this->roles_as_values(); 
	if(is_array($roles) === false) return false;
	$role_value = $roles[ $role ];
```

**Comment by the-plainview** [comment]
Hold on a second... Line 444 belongs to function role_at_least.

A text search of the whole Broadcast directory shows that that method is never called. What version of Broadcast are you on, even?

**Comment by noelboss** [comment]
I'm on Version 19.1

In my case, both $roles as well as $role are arrays...

This solves it for me, not sure if it should return true or false tough...
if(is_array($role) === true || is_array($roles) === false) return true;

**Comment by the-plainview** [comment]
You say row 444 of the wordpress base.php file in the SDK. That row belongs to method role_at_least().

Could you do a recursive search for role_at_least in your source, since I can't find it anywhere in mind except in that one file.

**Comment by noelboss** [comment]
The function is called (multiple times from premium_pack) – both $role and $roles are arrays (in certain circumstances probably) and the plugin should handle this situation... Also, since both values can be arrays, the test should probably be more advanced actually compare the two arrays...

**Comment by the-plainview** [comment]
Which version of the pack are you using? Current is 19.3

role_at_least has been deprecated since (1) a user can have multiple roles and (2) roles are not rankable, so "at least" no longer makes any sense.

**Comment by noelboss** [comment]
I'm using 16

**Comment by noelboss** [comment]
The function is not called anymore...

**Comment by noelboss** [comment]
Sorry for bothering you, the update did not show up so i thought it's the latest version.

**Comment by noelboss** [comment]
But then it would probably make sense now to remove the unused function(s?)

**Comment by the-plainview** [comment]
Generally you would be right, but the SDK is used by other plugins I have written and can't remove the method before the other plugins have been updated to not use the method.
