### ISSUE TITLE
Empty Blog Name

### ISSUE THREAD

**Issue by dmgawel** [the-plainview/threewp_broadcast#32]
When blog name is empty it is not possible to broadcast post to this blog. It's not displayed neither in post form metabox nor in maintenance blog access check but I have access to it and proper PHP variables contain it.

Possible fix: empty blog name should fall to site path (key) on blog model init.

**Comment by the-plainview** [comment]
How and why does one have a blog without a name?

**Comment by dmgawel** [comment]
*In the world of WordPress you should expect unexpectable.*

I've been asked for help with this case and found that site owner set logo containing company name. He couldn't find out how to hide text name so he simply deleted it in WP settings.

**Comment by the-plainview** [comment]
Wow. Unexpected indeed. I'll see what I can find in the source.

**Comment by the-plainview** [comment]
Would you mind e-mailing me to test the fix?
